services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
  
  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    secrets:
      - db_password
      - db_root_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - /home/samet/data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

networks:
  inception: 
    driver: bridge