version: '1'

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "8080:443"
    depends_on:
      - wordpress
    networks:
      - inception
  
  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    networks:
      - inception

networks:
  inception: